config/routes.rb
Bestdressworld::Application.routes.draw do
  root :to => 'application#homepage'
  get 'admin' => 'application#admin'
  match 'api_create_products' => 'products#api_create', :via => [:get, :post]
  get 'products/:seo_url' => 'products#show'
  resources :products do
    get 'page/:page', :action => :index, :on => :collection
  end

  get 'brands/new' => 'brands#new'
  get 'brands/:url_key' => 'brands#show'
  resources :brands do
    get 'page/:page', :action => :index, :on => :collection
  end

  match '/signup' => 'users#new'
  post 'users' => 'users#create'
  match '/login' => 'sessions#new'
  match '/logout' =>  'sessions#destroy'
  get '/auth/:provider/callback', :to => 'sessions#create'
  resources :sessions, :only => [:new, :create, :destroy]

  namespace :admin do |admin|
    get 'products/amazon' => 'products#amazon'
    resources :products
    resources :amazon
    match 'categories/create_for_product/:product_id' => 'categories#create_for_product'
    resources :categories
    resources :images
    match 'options/create_for_product/:product_id' => 'options#create_for_product'
    resources :options
  end

  resources :users, :path => "" do
    member do
      get :brands
      get :shares
      #get :likes
    end
  end
end

app/models/user.rb
#coding=utf-8
class User < ActiveRecord::Base
  acts_as_tagger

  attr_accessible :username, :email, :password, :password_confirmation # 这个地方很重要,否则前台可以伪造表单的role字段从而提升权限
  attr_protected :role
  has_secure_password

  validates :username, presence: true,
            format: {:with => /\A\w+\z/, :message => 'must contain only these characters: a-zA-Z0-9_'},
            length: { :in => 3..20 },
            uniqueness: {:case_sensitive => false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  has_one :brand
  has_many :identities
  has_many :products

  before_save { |user| user.email = email.downcase unless email.blank? }
  before_save :create_remember_token

  def has_role?(role)
    self.role == role.to_s
  end

  def self.find_or_create_with_omniauth(auth)
    identity = Identity.find_with_omniauth(auth)
    identity = Identity.create_with_omniauth(auth) if identity.blank?
    return identity.user if identity && identity.user
    user = User.new(username: 'sns_' + (identity.id+10086).to_s, nickname: identity.name)
    user.identities = [identity]
    user.save!(:validate => false)
    user
  end

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "user", :except => [:new, :create]
  before_filter :find_user, :except => [:new, :create]
  load_and_authorize_resource :only => [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = 'brand' unless params[:brand].blank?
    if @user.save
      self.current_user = @user
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def show

  end

  def likes

  end

  def brands

  end

  def shares
    @products = Product.desc.where({:user_id => @user.id}).page(params[:page]).per(8).decorate
    respond_to do |format|
      format.html
      format.js {render :template => 'products/waterfall' }
    end
  end

  protected
  def find_user
    @user = User.find_by_username(params[:id]).decorate
    render_404 if @user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_menu.html.erb
<ul class="nav nav-tabs">
  <li <%=nav_active('users', 'show')%>>
    <a href="<%=user_path(@user.username)%>"><i class="icon-user"></i> <%=@user.nickname.capitalize%></a>
  </li>
  <li<%=nav_active('users', 'shares')%>>
    <a href="<%=shares_user_path(@user.username)%>"><i class="icon-share"></i> Shares</a>
  </li>
  <li<%=nav_active('users', 'brands')%>>
    <a href="<%=brands_user_path(@user.username)%>"><i class="icon-map-marker"></i> Brands</a>
  </li>
</ul>

app/views/users/brands.html.erb
<% if @user.brand.blank? %>
<div class="text-center box padding10">
  <a href="<%= new_brand_path %>" class="btn btn-info"> create my own brand! </a>
</div>
<% else %>
  <% brand = @user.brand %>
  <div class="box padding10">
    <div class="pull-left" style="margin-right: 15px;">
      <p><img src="<%=@user.brand.logo%>"/></p>
      <% if can? :edit, brand %>
      <div class="text-center"><a href="<%=edit_brand_path(brand)%>" class="btn btn-info btn-block">Edit</a></div>
      <% end %>
    </div>
    <div>
      <p><strong><%=brand.name%></strong> <small>(<%=brand.slogan%>)</small></p>
      <p><strong>Website</strong>: <%=brand.website%></p>
      <p><strong>Since</strong>: <%=brand.year%></p>
      <p><strong>Good at</strong>: <%=brand.good_at%></p>
      <p><strong>Country</strong>: <%=brand.country%></p>
    </div>
    <div class="clearfix"></div>
    <div class="clearfix mt10">
      <blockquote><%=brand.introduce%></blockquote>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="sign">
  <h2>Join us today <small>Have an account? <a href="<%=login_path%>">login</a></small></h2>
  <p><small>Connect with a social network</small></p>
  <ul class="sns unstyled clearfix">
    <li><a class="twitter" href="/auth/twitter"><i></i>Twitter</a></li>
    <li><a class="facebook" href="/auth/facebook"><i></i>Facebook</a></li>
    <li class="last"><a class="google" href="/auth/google"><i></i>Google</a></li>
  </ul>

  <div class="line"></div>

  <p class="text-center other-way <%=@user.errors.blank? ? '' : 'hide'%>">
    <small>Sign up with
      <a onclick="$('#new_user').show();$('.other-way').hide();" href="javascript:void(0);"><b>your email address</b></a>
    </small>
  </p>

  <%= form_for(@user, :html => {:class => (@user.errors.blank? ? 'hide' : '')}) do |f| %>
      <input type="hidden" name="ret_url" value="<%= params[:ret_url] %>"/>
      <p><small>Sign up with your email address</small></p>
      <%= display_errors(@user) %>
      <p>
        <%= f.label :username %>
        <%= f.text_field :username, :class=>"large" %>
        <small>Your Private page: http://bestdressworld.com/<strong>USERNAME</strong></small>
      </p>

      <p><%= f.label :email %>
        <%= f.text_field :email %> </p>

      <p><%= f.label :password %>
        <%= f.password_field :password %></p>

      <p><%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %></p>

      <p>
        <label class="checkbox">
          <input name="brand" type="checkbox"> I'm a brand or store
          <i class="icon-question-sign"></i>
        </label>
      </p>

      <p class="btn-area"><%= f.submit "Create my account", class: "btn btn-large btn-block btn-info" %></p>
      <p class="text-center">
        <a onclick="$('#new_user').hide();$('.other-way').show();" href="javascript:void(0);"><small>go back</small></a>
      </p>
  <% end %>
</div>

app/views/users/shares.html.erb
<div class="alert">
  <div class="input-prepend input-append mb0">
    <form class="mb0" method="post" action="<%= products_path %>">
      <span class="add-on">amazon asin</span>
      <input type="hidden" name="ret_url" value="<%=request.url%>"/>
      <input class="span2" name="asin" type="text" value="<%= flash[:asin] %>"/>
      <button class="btn btn-info" type="submit">share!</button>
    </form>
  </div>
  <span style="margin-left: 20px; color: red; font-size: 12px;">
    <%=flash[:alert].map{|res| res[:msg]}.join("<br>") if flash[:alert].is_a?(Array)%>
    <%=flash[:alert] if flash[:alert].is_a?(String)%>
  </span>
</div>

<%= render "products/waterfall", :products => @products  %>

app/views/users/show.html.erb
<div class="box padding10">
  <h3 style="margin: 0;">Basic Info</h3>
  <dl class="dl-horizontal">
    <dt>nickname</dt>
    <dd><%=@user.nickname%></dd>
    <dt>created at</dt>
    <dd><%=@user.created_at.to_date%></dd>
  </dl>
</div>

<!--div class="mt15 box padding10">
  <h3 style="margin: 0;">Social Networks</h3>
  <% ['facebook', 'twitter', 'google'].each do |sns| %>
    <i class="<%=sns%>"></i>
  <% end %>
</div-->