config/routes.rb
Bestdressworld::Application.routes.draw do
  root :to => 'application#homepage'
  get 'admin' => 'application#admin'
  match 'api_create_products' => 'products#api_create', :via => [:get, :post]
  get 'products/:seo_url' => 'products#show'
  resources :products do
    get 'page/:page', :action => :index, :on => :collection
  end

  get 'brands/new' => 'brands#new'
  get 'brands/:url_key' => 'brands#show'
  resources :brands do
    get 'page/:page', :action => :index, :on => :collection
  end

  match '/signup' => 'users#new'
  post 'users' => 'users#create'
  match '/login' => 'sessions#new'
  match '/logout' =>  'sessions#destroy'
  get '/auth/:provider/callback', :to => 'sessions#create'
  resources :sessions, :only => [:new, :create, :destroy]

  namespace :admin do |admin|
    get 'products/amazon' => 'products#amazon'
    resources :products
    resources :amazon
    match 'categories/create_for_product/:product_id' => 'categories#create_for_product'
    resources :categories
    resources :images
    match 'options/create_for_product/:product_id' => 'options#create_for_product'
    resources :options
  end

  resources :users, :path => "" do
    member do
      get :brands
      get :shares
      #get :likes
    end
  end
end

app/models/category.rb
#coding=utf-8
class Category < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :children, :class_name => "Category", :foreign_key => "parent_id"
  has_and_belongs_to_many :products
  after_destroy {products.clear}
  belongs_to :parent, :class_name => "Category"

  validates_presence_of :code, :message => '分类名称不能为空'
  validates_uniqueness_of :code, :message => '%{value} 分类名称不能重复'
  validates_presence_of :url_key, :message => '必须指定分类在url中显示的字符串'

  def self.tree
    nodes = Hash.new
    self.order('parent_id ASC').all.each do |category|
      is_parent = true
      nodes.each do |parent, children|
        if (parent.id == category.parent_id)
          nodes[parent] << { category => [] }
          is_parent = false
          break
        end
      end
      nodes[category] = [] if is_parent
    end

    nodes
  end

  def name
    name_en
  end

  before_validation {
    self.code = self.code.strip.downcase unless self.code.blank?
    self.name_en = self.code if self.name_en.blank?
    if self.url_key.blank? && !self.name_en.blank?
      self.url_key = self.name_en.downcase.gsub(/[^\w\s]/, ' ').gsub(' ', '-')
    end
  }
end

app/controllers/admin/categories_controller.rb
#coding=utf-8
class Admin::CategoriesController < Admin::ApplicationController
  def index
    @categories = Category.where(:parent_id => 0).includes(:children).all
  end

  def new
    @category = Category.new(:parent_id => (params[:parent_id] || 0))
    respond_to do |format|
      format.html {render :template => 'admin/categories/new'}
      format.js { j render :layout => false, :template => 'admin/categories/new' }
    end
  end

  def create
    @category = Category.new(params[:category])
    #@category.save ? redirect_to(:action => :index) : render(:template => 'admin/categories/new')
    respond_to do |format|
      if @category.save
        format.html { redirect_to(:action => :index) }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html {render :template => 'admin/categories/edit'}
      format.js { j render :layout => false, :template => 'admin/categories/edit' }
    end
  end

  def update
    @category = Category.find(params[:category][:id])
    @category.update_attributes(params[:category]) ? redirect_to(:action => :index) : render(:template => 'admin/categories/edit')
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to :action => :index
  end

  def create_for_product
    @product = Product.find(params[:product_id])
    if request.post?
      cps = []
      params[:category].each do |category_id|
        cps << {:product_id => params[:product_id], :category_id => category_id}
      end
      @entities = CategoriesProduct.create(cps)
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
  def render_category_select()
    html="<select name='categories_select'>"
    Category.tree.each do |node, children|
      style = children.blank? ? '' : ' style="color: blue;"'
      html += "<option value='#{node.id}'#{style}>#{node.name}</option>"
      children.each do |child|
        child.each do |k, v|
          html += "<option value='#{k.id}'>#{k.name}</option>"
        end
        #render_category_select(child, html)
      end
    end

    (html+'</select>').html_safe
  end
end

app/views/admin/categories/_fields.html.erb
<%= f.hidden_field :id %>
<div class="control-group">
  <%= f.label :parent_id, :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :parent_id %>
  </div>
</div>

<div class="control-group">
  <%= f.label :code, :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :code %>
  </div>
</div>

<div class="control-group">
  <%= f.label :name_en, :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :name_en %>
  </div>
</div>

<div class="control-group">
  <%= f.label :name_cn, :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :name_cn %>
  </div>
</div>

<div class="control-group">
  <%= f.label :url_key, :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :url_key %>
  </div>
</div>

app/views/admin/categories/_tree_node.html.erb
<span><%= category.name %><%='('+category.name_cn+')' unless category.name_cn.blank?%></span>
<span class="actions" style="display: none;">
  <% if can?(:manage, category) %>
    <% if !category.children.blank? || category.parent_id == 0 %>
    <a class="add" title="添加子分类" href="<%= new_admin_category_url(:parent_id => category.id, :format=>'js') %>"><i class="icon-plus"></i></a> |
    <% end %>
    <a class="edit" title="编辑该分类" href="<%= edit_admin_category_url(category, :format=>'js') %>"><i class="icon-edit"></i></a> |
    <%= link_to content_tag(:i, '', 'class'=>'icon-remove'), admin_category_url(category), :confirm => "确定删除#{category.name}?", :method=>:delete, :title => "删除该分类"  %>
  <% end %>
</span>

app/views/admin/categories/create.js.erb
<% if @category.errors.any? %>
    $('#model .modal-body-content').html("<%= j render :template => 'admin/categories/new' %>");
    $('#model form').data('remote', true);
<% else %>
    $('#model form')[0].reset();
    $('#node<%=@category.parent_id%>').next('.children').append("<div class='node'  id='node<%=@category.id%>'><%= j render 'tree_node', :category => @category %></div>");
<% end %>

app/views/admin/categories/create_for_product.html.erb
<% category_names = []
   Category.tree.each do |parent, children|
    category_names << parent.name.gsub('dresses', '').gsub('dress', '')
    children.each do |child|
      category_names << child.map{|k, v| k.name}[0].gsub('dresses', '').gsub('dress', '')
    end
  end
%>

<div class="row-fluid">
    <div class="span3" style="max-height: 550px; overflow: auto;">
      <% @product.images.each do |image| %>
      <img src="<%=image.url%>" />
      <% end %>
    </div>
    <div class="span9">
      <%=@entities.map{|e| display_errors(e)}.join("").html_safe if !@entities.blank?%>
      <%= form_tag "", :class => "form-inline" do %>
        <input type="hidden" name="product_id" value="<%=@product.id%>"/>
        <div class="fs16"><strong><%=highlight(@product.name.downcase, category_names)%></strong>
          <%=@product.currency_symbol%><%=@product.price%>
        </div>
        <ul class="unstyled">
          <% Category.tree.each do |parent, children| %>
          <li class="mb10">
            <div>
              <label class="checkbox">
                <input <%=" checked=checked" if category_belongs_to_product?(parent, @product) %> type="checkbox" name="category[]" value="<%=parent.id%>"/>
                <strong <%=" style=color:red;" if category_belongs_to_product?(parent, @product) %>>
                  <%=parent.name%><%='('+parent.name_cn+')' unless parent.name_cn.blank?%>
                </strong>
              </label>
            </div>
            <div>
              <% children.each do |cate, arr| %>
                <label class="checkbox" style="min-width: 130px;">
                  <% category = cate.map{|k, v| k}[0] %>
                  <input <%=" checked=checked" if category_belongs_to_product?(category, @product) %> type="checkbox" name="category[]" value="<%=category.id%>"/>
                  <span <%=" style=color:red;" if category_belongs_to_product?(category, @product) %>>
                    <%=category.name%><%='('+category.name_cn+')' unless category.name_cn.blank?%>
                  </span>
                </label>
              <% end %>
            </div>
          </li>
          <% end %>
        </ul>

        <div>
          <% if @product.previous.blank? %>
              <span class="btn">没有了</span>
          <% else %>
              <a class="btn" href="<%=url_for(:controller => 'admin/categories', :action => 'create_for_product', :product_id => @product.previous.id)%>">上一个产品</a>
          <% end %>
          -
          <%= submit_tag "添加", :disable_with => "提交中...", :class=>"btn btn-primary"%>  -
          <% if @product.next.blank? %>
            <span class="btn">没有了</span>
          <% else %>
            <a class="btn" href="<%=url_for(:controller => 'admin/categories', :action => 'create_for_product', :product_id => @product.next.id)%>">下一个产品</a>
          <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/admin/categories/edit.html.erb
<div class="mb10">
  编辑分类 <span class="label label-info"><%= @category.name %></span>
</div>
<%= form_for [:admin, @category], :html => { :class => 'form-horizontal' } do |f| %>
    <% if @category.errors.any? %>
    <div>
      <ul class="unstyled well-small alert-error">
        <% for message in @category.errors.full_messages %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= render "fields", :f => f %>
    <div class="form-actions">
      <%= f.submit '提交', :class => 'btn btn-primary' %>
      <a href="<%= admin_categories_url %>" style="margin-left: 10px;"><i class="icon-share-alt"></i>返回分类管理</a>
    </div>
<% end %>

app/views/admin/categories/index.html.erb
<div class="pull-left tree">
  <div class="node">root
    <% if can?(:manage, Category) %>
    <a title="为根分类添加子分类" href="<%= new_admin_category_url(:parent_id => 0) %>"><i class="icon-plus"></i></a>
    <% end %>
  </div>
  <div class="children" id="children0">
    <% @categories.each_with_index do |category, index| %>
      <div class="node-group">
        <div class="node expandable" id="node<%=category.id%>">
          <div class="hitarea"></div><%= render "tree_node", :category => category %>
        </div>
        <% unless category.children.blank? %>
        <div class="children">
          <% category.children.each do |c| %>
          <div class="node" id="node<%=c.id%>"><%= render "tree_node", :category => c %> </div>
          <% end %>
        </div>
        <% else %>
          <div class="children" id="children<%=category.id%>"></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= render "admin/common/modal" %>

<script>
    $(document).ready(function() {
        $('.node').mouseover(function() {
            $(this).find('.actions').show();
        }).mouseout(function(){
            $(this).find('.actions').hide();
        });
        //
        $('.actions .add, .actions .edit').click(function() {
            util.modal($(this).attr("href"));
            return false;
        });
    });
</script>

app/views/admin/categories/new.html.erb
<%= form_for [:admin, @category], :remote => (params[:format] == 'js' ? true : false),:html => { :class => 'form-horizontal' } do |f| %>
    <legend>为分类 <span class="label label-info"><%= @category.parent.blank? ? 'root' : @category.parent.name %></span> 添加子分类：</legend>
    <% if @category.errors.any? %>
    <div>
      <ul class="unstyled well-small alert-error">
        <% for message in @category.errors.full_messages %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= render "fields", :f => f %>
    <div class="form-actions">
      <%= f.submit '提交', :class => 'btn btn-primary' %>
      <a href="<%= admin_categories_url %>" style="margin-left: 10px;"><i class="icon-share-alt"></i>返回分类管理</a>
    </div>
<% end %>