config/routes.rb
Bestdressworld::Application.routes.draw do
  root :to => 'application#homepage'
  get 'admin' => 'application#admin'
  match 'api_create_products' => 'products#api_create', :via => [:get, :post]
  get 'products/:seo_url' => 'products#show'
  resources :products do
    get 'page/:page', :action => :index, :on => :collection
  end

  get 'brands/new' => 'brands#new'
  get 'brands/:url_key' => 'brands#show'
  resources :brands do
    get 'page/:page', :action => :index, :on => :collection
  end

  match '/signup' => 'users#new'
  post 'users' => 'users#create'
  match '/login' => 'sessions#new'
  match '/logout' =>  'sessions#destroy'
  get '/auth/:provider/callback', :to => 'sessions#create'
  resources :sessions, :only => [:new, :create, :destroy]

  namespace :admin do |admin|
    get 'products/amazon' => 'products#amazon'
    resources :products
    resources :amazon
    match 'categories/create_for_product/:product_id' => 'categories#create_for_product'
    resources :categories
    resources :images
    match 'options/create_for_product/:product_id' => 'options#create_for_product'
    resources :options
  end

  resources :users, :path => "" do
    member do
      get :brands
      get :shares
      #get :likes
    end
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  # attr_accessible :title, :body
  validates :name, :presence => true, :uniqueness => true
  validates :url_key, :presence => true, :uniqueness => true
  validates :introduce, :presence => true, :length => {:maximum => 2000}

  belongs_to :user

  before_validation do
    name = self.name.gsub(/\W/, "")
    self.url_key = name if self.url_key.blank? && name
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to login_url, :alert => exception.message
  end
  def index
    @brands = Brand.order("id DESC").page(params[:page]).per(19)
  end

  def show
    @brand = Brand.find_by_url_key(params[:url_key])
    @brand = Brand.find(params[:url_key]) if @brand.blank?
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params[:brand])
    @brand.user_id = current_user.id
    @brand.save ? redirect_to(:action => :index) : render(:action => :new)
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    @brand.update_attributes(params[:brand]) ? redirect_to(:action => :index) : render(:action => :edit)
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_fields.html.erb
<%= f.hidden_field :id %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :url_key %>
  <%= f.text_field :url_key %>
</div>
<div>
  <%= f.label :slogan %>
  <%= f.text_field :slogan %>
</div>
<div>
  <%= f.label :year, "Since" %>
  <%= f.text_field :year %>
</div>
<div>
  <%= f.label :country %>
  <%= f.text_field :country %>
</div>
<div>
  <%= f.label :website %>
  <%= f.text_field :website %>
</div>
<div>
  <%= f.label :good_at, "Good at" %>
  <%= f.text_field :good_at %>
</div>
<div>
  <%= f.label :logo %>
  <%= f.text_field :logo %>
</div>
<div>
  <%= f.label :introduce, "Story" %>
  <%= f.text_area :introduce %>
</div>

app/views/brands/edit.html.erb
<% provide(:title, 'edit brand: '+ @brand.name) %>

<%= form_for @brand,:html => { :class => 'form-horizontal form-large box padding10' } do |f| %>
  <div><%=display_errors(@brand)%></div>
  <%=render "fields", :f=>f%>
  <div class="mt10">
    <%=f.submit :class => 'btn btn-info'%>
  </div>
<% end %>

app/views/brands/index.html.erb
<% provide(:title, "all brands in bestdressworld.com") %>
<ul class="brands box clearfix unstyled">
  <% @brands.each_with_index do |brand, index| %>
  <li <%= "class=right-last" if (index+1) % 5 == 0 %>>
    <% brand_url = brand_path(brand.url_key.blank? ? brand.id : brand.url_key) %>
    <div class="logo"><a title="<%=brand.name%>" href="<%= brand_url %>"><img src="<%=brand.logo%>"/></a></div>
    <div class="slogan"><a href="<%= brand_url %>"><%= brand.slogan.blank? ? brand.name : brand.slogan %></a></div>
  </li>
  <% end %>
  <li<%= "class=right-last" if (@brands.size+1) % 5 == 0 %>>
    <div class="logo"><a title="Create Your Own Brand!" href="<%=new_brand_path%>" style="font-size: 38px; color: #666;">+</a></div>
    <div class="slogan"><a href="<%= new_brand_path %>">Create Your Own Brand!</a></div>
  </li>
</ul>

app/views/brands/new.html.erb
<% provide(:title, 'create your own brand on bestdressworld.com') %>

<%= form_for @brand,:html => { :class => 'form-large box padding10' } do |f| %>
  <div><%=display_errors(@brand)%></div>
  <%= render "fields", :f => f %>
  <div class="mt10">
    <%=f.submit :class => 'btn btn-info'%>
  </div>
<% end %>

app/views/brands/show.html.erb
<% provide(:title, @brand.name) %>
<% provide(:description, @brand.introduce) %>
<div class="row">
  <div class="span9">
    <div class="box padding10">
      <p class="fs16"><strong>all products of <%= @brand.name %></strong></p>
    </div>
  </div>
  <div class="span3">
    <div class="box padding10 text-center mb15">
      <div><img src="<%=@brand.logo%>"/></div>
      <div><%=@brand.name%></div>
      <div><%=@brand.slogan%></div>
    </div>

    <div class="box padding10 mb15">
      <p>Brand Profile</p>
      <div>Name: <%=@brand.name%></div>
      <div>Country: <%=@brand.country%></div>
      <div>Since: <%=@brand.year%></div>
      <div>Good at: <%=@brand.good_at%></div>
      <div>Website: <a href="<%= @brand.website%>" target="_blank"><%= @brand.website%></a></div>
    </div>

    <div class="box padding10">
      <p>brand story</p>
      <div><%=strip_tags(@brand.introduce)%></div>
    </div>
  </div>
</div>