config/routes.rb
Bestdressworld::Application.routes.draw do
  root :to => 'application#homepage'
  get 'admin' => 'application#admin'
  match 'api_create_products' => 'products#api_create', :via => [:get, :post]
  get 'products/:seo_url' => 'products#show'
  resources :products do
    get 'page/:page', :action => :index, :on => :collection
  end

  get 'brands/new' => 'brands#new'
  get 'brands/:url_key' => 'brands#show'
  resources :brands do
    get 'page/:page', :action => :index, :on => :collection
  end

  match '/signup' => 'users#new'
  post 'users' => 'users#create'
  match '/login' => 'sessions#new'
  match '/logout' =>  'sessions#destroy'
  get '/auth/:provider/callback', :to => 'sessions#create'
  resources :sessions, :only => [:new, :create, :destroy]

  namespace :admin do |admin|
    get 'products/amazon' => 'products#amazon'
    resources :products
    resources :amazon
    match 'categories/create_for_product/:product_id' => 'categories#create_for_product'
    resources :categories
    resources :images
    match 'options/create_for_product/:product_id' => 'options#create_for_product'
    resources :options
  end

  resources :users, :path => "" do
    member do
      get :brands
      get :shares
      #get :likes
    end
  end
end

app/views/common/_footer.html.erb
<div class="footer">
  <div class="mb10" style="border-bottom: #fff 1px solid; border-top: #E8E8E8 1px solid;">
  </div>
  <div class="container">
    <div class="text-center">© 2013 <a href="<%= root_url %>">best dress world</a></div>
  </div>
</div>

app/views/common/_ga.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-40773874-1', 'bestdressworld.com');
    ga('send', 'pageview');

</script>

<script type="text/javascript">
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fdcc5def8f14fb8cd7b052369b89365a3' type='text/javascript'%3E%3C/script%3E"));
</script>

app/views/common/_head_meta.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><%= !yield(:title).blank? ? yield(:title) : 'BestDressWorld.com: Find The Best Dress In The World!' %></title>
<meta name="keywords" content="<%= yield(:keywords) %>">
<meta name="description" content="<%= yield(:description) %>">
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= stylesheet_link_tag params[:controller] %>
<%= yield(:stylesheet) %>
<%= render "common/ga" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag params[:controller] %>
<%= yield(:javascript) %>
<%= csrf_meta_tags %>

app/views/common/_header.html.erb
<div class="header">
  <div class="nav-bar">
    <div class="container text-center">
      <ul class="nav-main pull-left unstyled">
        <li><a <%=nav_active(nil, 'homepage')%> href="<%= root_url %>"><i class="icon-home"></i> Home</a></li>
        <li class="split"><a <%=nav_active('products')%> href="<%= products_url %>">Products</a></li>
        <!--li class="split"><a <%=nav_active('brands')%> href="<%= brands_url %>">Brands</a></li-->
      </ul>
      <a href="<%= root_url %>"><img style="height: 25px;" src="<%= asset_path('logo.png') %>"/></a>
      <div class="pull-right" style="margin-top: 3px;">
        <% if signed_in? %>
            <div class="input-append">
              <a class="btn btn-small" href="<%=user_path(current_user.username)%>">
                <i class="icon-user"></i>
                <%=current_user.nickname%>
                <!--b class="caret"></b-->
              </a>
              <a class="btn btn-small" href="<%= logout_path(:ret_url => request.url) %>"><i class="icon-off"></i> logout</a>
            </div>
        <% else %>
            <div class="input-append">
              <a class="btn btn-small" href="<%=login_url(:ret_url => request.url)%>">login</a>
              <a class="btn btn-small" href="<%=signup_url(:ret_url => request.url)%>">sign up </a>
            </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="bottom"></div>
</div>